<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPKLA6ZS\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPKLA6ZS/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerPKLA6ZS.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerPKLA6ZS\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerPKLA6ZS\App_KernelProdContainer([
    'container.build_hash' => 'PKLA6ZS',
    'container.build_id' => 'f8a057eb',
    'container.build_time' => 1700037938,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPKLA6ZS');
