<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEqhgxCt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEqhgxCt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEqhgxCt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEqhgxCt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEqhgxCt\App_KernelDevDebugContainer([
    'container.build_hash' => 'EqhgxCt',
    'container.build_id' => '56331544',
    'container.build_time' => 1699869012,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEqhgxCt');
